# Generated by Django 3.2.6 on 2021-08-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0007_auto_20210807_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratory_name', models.CharField(default='', max_length=120)),
                ('laboratory_state', models.CharField(default='Delhi', max_length=30)),
                ('laboratory_city', models.CharField(default='Delhi', max_length=30)),
                ('laboratory_area', models.CharField(default='Civil Lines', max_length=120)),
                ('laboratory_pincode', models.IntegerField(default='110054')),
                ('laboratory_address', models.CharField(default='Civil Lines', max_length=120)),
                ('laboratory_rent', models.IntegerField(default='6000')),
                ('laboratory_deposit', models.IntegerField(default='5000')),
                ('laboratory_contactnumber', models.IntegerField(default='+91')),
                ('laboratory_mess', models.IntegerField(default='1')),
                ('laboratory_mealtype', models.CharField(default='veg', max_length=120)),
                ('laboratory_bloodtest', models.IntegerField(default='1')),
                ('laboratory_ctscan', models.IntegerField(default='1')),
                ('laboratory_xray', models.IntegerField(default='1')),
                ('labrotory_corona', models.IntegerField(default='1')),
                ('labrotory_description', models.TextField(default='veg food allowed, A.C provided, washing machine available, iron availble, Geyser provided', max_length=500)),
                ('labrotory_images1', models.ImageField(default='', upload_to='display/img/laboratory_images')),
                ('labrotory_image2', models.ImageField(default='', upload_to='display/img/laboratory_images')),
            ],
        ),
    ]
