# Generated by Django 3.2.6 on 2021-08-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0008_laboratory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboratory',
            old_name='laboratory_name',
            new_name='labroatory_name',
        ),
    ]
