# Generated by Django 3.2.6 on 2021-08-07 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0009_rename_laboratory_name_laboratory_labroatory_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboratory',
            old_name='labroatory_name',
            new_name='laboratory_name',
        ),
    ]
