# Generated by Django 3.2.6 on 2021-08-07 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0010_rename_labroatory_name_laboratory_laboratory_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboratory',
            old_name='labrotory_corona',
            new_name='laboratory_corona',
        ),
        migrations.RenameField(
            model_name='laboratory',
            old_name='labrotory_description',
            new_name='laboratory_description',
        ),
        migrations.RenameField(
            model_name='laboratory',
            old_name='labrotory_image2',
            new_name='laboratory_image2',
        ),
        migrations.RenameField(
            model_name='laboratory',
            old_name='labrotory_images1',
            new_name='laboratory_images1',
        ),
    ]
