# Generated by Django 3.2.6 on 2021-08-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0012_auto_20210808_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='laboratory_address',
            field=models.CharField(default='Muzaffarpur', max_length=120),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='laboratory_area',
            field=models.CharField(default='Juran Chhapra', max_length=120),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='laboratory_city',
            field=models.CharField(default='Muzaffarpur', max_length=30),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='laboratory_description',
            field=models.TextField(default='This lab is certified  byCAP (College of American Pathologists) and Certified by ISO 9001 (International Organization of Standardization).', max_length=500),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='laboratory_state',
            field=models.CharField(default='Bihar', max_length=30),
        ),
    ]
