# Generated by Django 3.2.6 on 2021-08-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0013_auto_20210808_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='laboratory_rent',
            field=models.IntegerField(default='500'),
        ),
    ]
